/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Auto;


import Controller.AutoController;
import Model.Auto;


import javax.swing.*;
import java.util.List;

import static View.Index.mostrarPanel;

/**
 *
 * @author Compumar
 */
public class FormAuto extends javax.swing.JPanel {


    private AutoController autoController = new AutoController();

    private boolean isUpdate = false; // Variable para indicar si es una actualización o creación de auto
    private Auto autoExistente; // Variable para almacenar el auto a actualizar

    /**
     * Creates new form FormAuto
     */
    public FormAuto() {
        initComponents();

    }


    public FormAuto(boolean isUpdate, Auto auto) {

        this.isUpdate = isUpdate;

        this.autoExistente = auto;

        initComponents();

        //refreshAutos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMarca = new javax.swing.JLabel();
        inputMarca = new javax.swing.JTextField();
        labelModelo = new javax.swing.JLabel();
        inputModelo = new javax.swing.JTextField();
        labelKilometraje = new javax.swing.JLabel();
        inputKilometraje = new javax.swing.JTextField();
        labelDisponible = new javax.swing.JLabel();
        btnFormAuto = new javax.swing.JButton();
        inputAutoDisponible = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(927, 590));

        labelMarca.setText("Marca");

        inputMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMarcaActionPerformed(evt);
            }
        });

        labelModelo.setText("Modelo");

        inputModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputModeloActionPerformed(evt);
            }
        });

        labelKilometraje.setText("Kilometraje");

        inputKilometraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKilometrajeActionPerformed(evt);
            }
        });

        labelDisponible.setText("¿Esta disponible el auto? (check --> si)");

        btnFormAuto.setText("Crear Auto");
        btnFormAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormAutoActionPerformed(evt);
            }
        });

        inputAutoDisponible.setText("Auto disponible");

        if(this.isUpdate){

            btnFormAuto.setText("Actualizar Auto");

            inputMarca.setText(autoExistente.getMarca());
            inputModelo.setText(autoExistente.getModelo());
            inputKilometraje.setText(String.valueOf(autoExistente.getKilometraje()));
            inputAutoDisponible.setSelected(autoExistente.isDisponible());

        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(labelMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputAutoDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(labelModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFormAuto, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(labelKilometraje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputKilometraje, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelKilometraje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addComponent(labelDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAutoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(btnFormAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMarcaActionPerformed

    }//GEN-LAST:event_inputMarcaActionPerformed

    private void inputModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputModeloActionPerformed

    }//GEN-LAST:event_inputModeloActionPerformed

    private void inputKilometrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKilometrajeActionPerformed

    }//GEN-LAST:event_inputKilometrajeActionPerformed

    private void btnFormAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormAutoActionPerformed
        String marca = inputMarca.getText();
        String modelo = inputModelo.getText();
        String kilometrajeStr = inputKilometraje.getText();
        Boolean autoDisponible = inputAutoDisponible.isSelected();

        // Valido que no haya campos vacíos
        if (marca.isEmpty() || modelo.isEmpty() || kilometrajeStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
            return;
        }

        // Valido que el dni y el celular sean números válidos
        double kilometraje;
        try {
            kilometraje = Double.parseDouble(kilometrajeStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El DNI y el celular deben ser números válidos.");
            return;
        }

        // Valido que el dni y el celular sean mayores a 0

        if (kilometraje <= 0) {
            JOptionPane.showMessageDialog(this, "El dni y el celular deben ser mayores a 0.");
            return;
        }

        if(this.isUpdate){

            // Si es una actualización, modifico el auto existente

            autoExistente.setMarca(marca);
            autoExistente.setModelo(modelo);
            autoExistente.setKilometraje(kilometraje);
            autoExistente.setDisponible(autoDisponible);

            autoController.update(autoExistente);

        }else{
            autoController.create(new Auto(kilometraje, marca, modelo, autoDisponible));
        }


        mostrarPanel(new ListadoAuto());

    }//GEN-LAST:event_btnFormAutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormAuto;
    private javax.swing.JCheckBox inputAutoDisponible;
    private javax.swing.JTextField inputKilometraje;
    private javax.swing.JTextField inputMarca;
    private javax.swing.JTextField inputModelo;
    private javax.swing.JLabel labelDisponible;
    private javax.swing.JLabel labelKilometraje;
    private javax.swing.JLabel labelMarca;
    private javax.swing.JLabel labelModelo;
    // End of variables declaration//GEN-END:variables
}
