/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Auto;

import Controller.AutoController;
import Model.Auto;
import Model.Chofer;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import static View.Index.mostrarPanel;

/**
 *
 * @author Compumar
 */
public class ListadoAuto extends javax.swing.JPanel {

    private AutoController autoController;

    /**
     * Creates new form ListadoAuto
     */
    public ListadoAuto() {

        initComponents();

        this.autoController = new AutoController();

        refreshTable();
    }

    public void refreshTable() {

        DefaultTableModel tableModel = new DefaultTableModel();

        tableModel.addColumn("Id");
        tableModel.addColumn("Marca");
        tableModel.addColumn("Modelo");
        tableModel.addColumn("Kilometraje");
        tableModel.addColumn("Disponible");
        tlListadoAuto.setModel(tableModel);


        for(Auto auto : autoController.readAll()) {
            Object[] row = new Object[5];

            row[0] = auto.getId();
            row[1] = auto.getMarca();
            row[2] = auto.getModelo();
            row[3] = auto.getKilometraje();
            row[4] = auto.isDisponible() ? "Disponible" : "No Disponible";


            tableModel.addRow(row);

        }

        tlListadoAuto.setModel(tableModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tlListadoAuto = new javax.swing.JTable();
        btnCrearAuto = new javax.swing.JButton();
        btnEditarAuto = new javax.swing.JButton();
        btnBorrarAuto = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(952, 598));

        tlListadoAuto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Marca", "Modelo", "Kilometros", "Disponible"
            }
        ));
        jScrollPane1.setViewportView(tlListadoAuto);

        btnCrearAuto.setBackground(new java.awt.Color(12, 85, 199));
        btnCrearAuto.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearAuto.setText("Crear auto");
        btnCrearAuto.setBorderPainted(false);
        btnCrearAuto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearAutoActionPerformed(evt);
            }
        });

        btnEditarAuto.setBackground(new java.awt.Color(12, 85, 199));
        btnEditarAuto.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarAuto.setText("Editar auto");
        btnEditarAuto.setBorderPainted(false);
        btnEditarAuto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAutoActionPerformed(evt);
            }
        });

        btnBorrarAuto.setBackground(new java.awt.Color(12, 85, 199));
        btnBorrarAuto.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarAuto.setText("Borrar auto");
        btnBorrarAuto.setBorderPainted(false);
        btnBorrarAuto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarAutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBorrarAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditarAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCrearAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAutoActionPerformed
        mostrarPanel(new FormAuto());
    }//GEN-LAST:event_btnCrearAutoActionPerformed

    private void btnEditarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAutoActionPerformed

        //Primero verifico que haya un auto seleccionado

        int selectedRow = tlListadoAuto.getSelectedRow();

        if (selectedRow < 0) {

            // Si no hay fila seleccionada, muestro un mensaje de error

            JOptionPane.showMessageDialog(this, "Por favor, seleccione un auto para editar.");

        }else{

            // Si hay fila seleccionada, obtengo el id del auto y muestro el panel de edicion

            int autoId = (int) tlListadoAuto.getValueAt(selectedRow, 0);

            // Muestro el panel de edicion de auto, llamando al metodo read, que me devuelve el auto con el id seleccionado.
            mostrarPanel(new FormAuto(true, autoController.read(autoId)));
        }
    }//GEN-LAST:event_btnEditarAutoActionPerformed

    private void btnBorrarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarAutoActionPerformed

        int selectedRow = tlListadoAuto.getSelectedRow();

        if (selectedRow < 0) {

            // Si no hay fila seleccionada, muestro un mensaje de error

            JOptionPane.showMessageDialog(this, "Por favor, seleccione un auto para borrar.");

        } else {

            // Si hay fila seleccionada, obtengo el id del auto

            int autoId = (int) tlListadoAuto.getValueAt(selectedRow, 0);

            // Confirmo la accion de borrado

            int confirmarAccion = JOptionPane.showConfirmDialog(this, "¿Desea borrar este auto?", "Confirmar accion", JOptionPane.YES_NO_OPTION);

            if (confirmarAccion == JOptionPane.YES_OPTION) {

                // Llamo al metodo delete del controlador de autos

                autoController.delete(autoId);

                // Actualizo la tabla

                refreshTable();
            }
        }
    }//GEN-LAST:event_btnBorrarAutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarAuto;
    private javax.swing.JButton btnCrearAuto;
    private javax.swing.JButton btnEditarAuto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tlListadoAuto;
    // End of variables declaration//GEN-END:variables
}
