/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Balances;

import Controller.ViajeController;
import DTO.BalanceMensualDTO;

/**
 *
 * @author Compumar
 */
public class BalanceMensual extends javax.swing.JPanel {

    ViajeController viajeController = new ViajeController();

    /**
     * Creates new form BalanceMensual
     */
    public BalanceMensual() {
        initComponents();
        setBalance();
    }

    public void setBalance(){

        BalanceMensualDTO balance = viajeController.getBalanceMensual();

        //int cantidadViajesTotal, float gananciaMensualRemiseria, float promedioSueldoMensualChoferSinAuto,
        //float promedioSueldoMensualChoferConAuto, float gananciaMensualChoferSinAuto, float gananciaMensualChoferConAuto, float promedioViajesPorChofer

        mostrarCantidadViajes.setText(String.valueOf(balance.getCantidadViajesTotal()));
        mostrarPromedioViajesChofer.setText(String.valueOf(balance.getPromedioViajesPorChofer()));
        mostrarPromedioMensualChoferConAuto.setText(String.valueOf(balance.getPromedioSueldoMensualChoferConAuto()));
        mostrarPromedioMensualChoferSinAuto.setText(String.valueOf(balance.getPromedioSueldoMensualChoferSinAuto()));
        mostrarGananciaMensualChoferConAuto.setText(String.valueOf(balance.getGananciaMensualChoferConAuto()));
        mostrarGananciaMensualChoferSinAuto.setText(String.valueOf(balance.getGananciaMensualChoferSinAuto()));
        gananciaMensual.setText(String.valueOf(balance.getGananciaMensualRemiseria()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        labelTitulo = new javax.swing.JLabel();
        labelCantidadViajes = new javax.swing.JLabel();
        mostrarCantidadViajes = new javax.swing.JLabel();
        mostrarPromedioViajesChofer = new javax.swing.JLabel();
        labelPromedioViajesChofer = new javax.swing.JLabel();
        labelPromedioMensualChoferConAuto = new javax.swing.JLabel();
        mostrarPromedioMensualChoferConAuto = new javax.swing.JLabel();
        labelPromedioMensualChoferSinAuto = new javax.swing.JLabel();
        mostrarPromedioMensualChoferSinAuto = new javax.swing.JLabel();
        labelGananciaMensualChoferConAuto = new javax.swing.JLabel();
        mostrarGananciaMensualChoferConAuto = new javax.swing.JLabel();
        labelGananciaMensualChoferSinAuto = new javax.swing.JLabel();
        mostrarGananciaMensualChoferSinAuto = new javax.swing.JLabel();
        labelGananciaMensual = new javax.swing.JLabel();
        gananciaMensual = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(927, 590));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitulo.setText("En este panel podras ver el balance mensual");

        labelCantidadViajes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCantidadViajes.setText("Cantidad de viajes:");

        mostrarCantidadViajes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mostrarPromedioViajesChofer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        labelPromedioViajesChofer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelPromedioViajesChofer.setText("Promedio viajes por chofer:");

        labelPromedioMensualChoferConAuto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelPromedioMensualChoferConAuto.setText("Promedio mensual por chofer con auto propio:");

        mostrarPromedioMensualChoferConAuto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        labelPromedioMensualChoferSinAuto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelPromedioMensualChoferSinAuto.setText("Promedio mensual por chofer sin auto propio:");

        mostrarPromedioMensualChoferSinAuto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        labelGananciaMensualChoferConAuto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelGananciaMensualChoferConAuto.setText("Ganancia mensual por choferes con auto:");

        mostrarGananciaMensualChoferConAuto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        labelGananciaMensualChoferSinAuto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelGananciaMensualChoferSinAuto.setText("Ganancia mensual por choferes sin auto:");

        mostrarGananciaMensualChoferSinAuto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        labelGananciaMensual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelGananciaMensual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGananciaMensual.setText("Total de ganancia mensual");

        gananciaMensual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gananciaMensual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCantidadViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mostrarCantidadViajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPromedioViajesChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mostrarPromedioViajesChofer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(labelGananciaMensualChoferSinAuto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mostrarGananciaMensualChoferSinAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(labelGananciaMensualChoferConAuto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mostrarGananciaMensualChoferConAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPromedioMensualChoferSinAuto)
                                    .addComponent(labelPromedioMensualChoferConAuto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mostrarPromedioMensualChoferConAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mostrarPromedioMensualChoferSinAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelGananciaMensual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gananciaMensual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mostrarCantidadViajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCantidadViajes, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(labelGananciaMensual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelPromedioViajesChofer, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(mostrarPromedioViajesChofer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mostrarPromedioMensualChoferConAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPromedioMensualChoferConAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPromedioMensualChoferSinAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mostrarPromedioMensualChoferSinAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelGananciaMensualChoferConAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mostrarGananciaMensualChoferConAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelGananciaMensualChoferSinAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mostrarGananciaMensualChoferSinAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(gananciaMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gananciaMensual;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelCantidadViajes;
    private javax.swing.JLabel labelGananciaMensual;
    private javax.swing.JLabel labelGananciaMensualChoferConAuto;
    private javax.swing.JLabel labelGananciaMensualChoferSinAuto;
    private javax.swing.JLabel labelPromedioMensualChoferConAuto;
    private javax.swing.JLabel labelPromedioMensualChoferSinAuto;
    private javax.swing.JLabel labelPromedioViajesChofer;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel mostrarCantidadViajes;
    private javax.swing.JLabel mostrarGananciaMensualChoferConAuto;
    private javax.swing.JLabel mostrarGananciaMensualChoferSinAuto;
    private javax.swing.JLabel mostrarPromedioMensualChoferConAuto;
    private javax.swing.JLabel mostrarPromedioMensualChoferSinAuto;
    private javax.swing.JLabel mostrarPromedioViajesChofer;
    // End of variables declaration//GEN-END:variables
}
