/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Balances;

import Controller.ViajeController;
import DTO.SemanaChoferDTO;

import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;

/**
 *
 * @author Compumar
 */
public class LiquidarSemana extends javax.swing.JPanel {

    ViajeController viajeController = new ViajeController();

    /**
     * Creates new form LiquidarSemana
     */
    public LiquidarSemana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tlCerrarSemana = new javax.swing.JTable();
        btnCerrarSemana = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(927, 590));

        tlCerrarSemana.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Chofer", "Cantidad de viajes", "Cantidad de km", "Semana"
            }
        ));
        jScrollPane1.setViewportView(tlCerrarSemana);

        btnCerrarSemana.setBackground(new java.awt.Color(12, 85, 199));
        btnCerrarSemana.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSemana.setText("Cerrar Semana");
        btnCerrarSemana.setBorderPainted(false);
        btnCerrarSemana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSemanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(btnCerrarSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSemanaActionPerformed

        LocalDateTime fechaInicio = LocalDateTime.now().minusDays(7);

        LocalDateTime fechaFin = LocalDateTime.now();

        refreshTable(fechaInicio, fechaFin);

     
    }//GEN-LAST:event_btnCerrarSemanaActionPerformed

    private void refreshTable(LocalDateTime fechaInicio, LocalDateTime fechaFin) {

        DefaultTableModel tableModel = new DefaultTableModel();

        tableModel.addColumn("Id");
        tableModel.addColumn("Chofer");
        tableModel.addColumn("Cantidad de viajes");
        tableModel.addColumn("Cantidad de km");
        tableModel.addColumn("Semana");
        tlCerrarSemana.setModel(tableModel);



        for(SemanaChoferDTO semanaChofer : viajeController.getSemanaChofer(fechaInicio, fechaFin)) {
            Object[] row = new Object[5];

            row[0] = semanaChofer.getChofer().getId();
            row[1] = semanaChofer.getChofer().getNombre();
            row[2] = semanaChofer.getCantidadViajes();
            row[3] = semanaChofer.getCantidadKilometros();
            row[4] = semanaChofer.getSueldoSemanal();


            tableModel.addRow(row);

        }

        tlCerrarSemana.setModel(tableModel);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSemana;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tlCerrarSemana;
    // End of variables declaration//GEN-END:variables
}
