/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.Balances.BalanceMensual;
import View.Chofer.ListadoChofer;
import View.Balances.LiquidarSemana;
import View.Viajes.ListadoViajes;
import View.Auto.ListadoAuto;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Compumar
 */
public class Index extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Index.class.getName());

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        //cargo la vista de los viajes ni bien inicio la app
        InitViajes();
    }

    // Metodo que inicializa la vista de los viajes
    private void InitViajes(){

        mostrarPanel(new ListadoViajes());
           
    }

    //Creo un metodo que reciba el panel que debe mostrarse en el content para realizar la navegacion

    public static void mostrarPanel(JPanel panel){

        panel.setSize(content.getSize());
        content.setLayout(new BorderLayout());
        panel.setLocation(0, 0);
        content.removeAll();
        content.add(panel);
        content.revalidate();
        content.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        linkChofer = new javax.swing.JButton();
        linkAuto = new javax.swing.JButton();
        linkBalance = new javax.swing.JButton();
        linkCerrarSemanaChofer = new javax.swing.JButton();
        linkViajes = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));

        menu.setBackground(new java.awt.Color(13, 71, 161));

        linkChofer.setBackground(new java.awt.Color(12, 85, 199));
        linkChofer.setForeground(new java.awt.Color(255, 255, 255));
        linkChofer.setText("Chofer");
        linkChofer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        linkChofer.setBorderPainted(false);
        linkChofer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkChofer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        linkChofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkChoferActionPerformed(evt);
            }
        });

        linkAuto.setBackground(new java.awt.Color(12, 85, 199));
        linkAuto.setForeground(new java.awt.Color(255, 255, 255));
        linkAuto.setText("Autos");
        linkAuto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        linkAuto.setBorderPainted(false);
        linkAuto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkAuto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        linkAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkAutoActionPerformed(evt);
            }
        });

        linkBalance.setBackground(new java.awt.Color(12, 85, 199));
        linkBalance.setForeground(new java.awt.Color(255, 255, 255));
        linkBalance.setText("Balance mensual");
        linkBalance.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        linkBalance.setBorderPainted(false);
        linkBalance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkBalance.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        linkBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkBalanceActionPerformed(evt);
            }
        });

        linkCerrarSemanaChofer.setBackground(new java.awt.Color(12, 85, 199));
        linkCerrarSemanaChofer.setForeground(new java.awt.Color(255, 255, 255));
        linkCerrarSemanaChofer.setText("Liquidar semana a choferes");
        linkCerrarSemanaChofer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        linkCerrarSemanaChofer.setBorderPainted(false);
        linkCerrarSemanaChofer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkCerrarSemanaChofer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        linkCerrarSemanaChofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkCerrarSemanaChoferActionPerformed(evt);
            }
        });

        linkViajes.setBackground(new java.awt.Color(12, 85, 199));
        linkViajes.setForeground(new java.awt.Color(255, 255, 255));
        linkViajes.setText("Viajes");
        linkViajes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        linkViajes.setBorderPainted(false);
        linkViajes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkViajes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        linkViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkViajesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linkChofer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(linkAuto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(linkBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
            .addComponent(linkViajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(linkCerrarSemanaChofer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(linkViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linkChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linkAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linkCerrarSemanaChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linkBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        header.setBackground(new java.awt.Color(13, 71, 161));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );

        content.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 927, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void linkChoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkChoferActionPerformed
        mostrarPanel(new ListadoChofer());
    }//GEN-LAST:event_linkChoferActionPerformed

    private void linkAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkAutoActionPerformed
        mostrarPanel(new ListadoAuto());
    }//GEN-LAST:event_linkAutoActionPerformed

    private void linkBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkBalanceActionPerformed
        mostrarPanel(new BalanceMensual());
    }//GEN-LAST:event_linkBalanceActionPerformed

    private void linkCerrarSemanaChoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkCerrarSemanaChoferActionPerformed
        mostrarPanel(new LiquidarSemana());
    }//GEN-LAST:event_linkCerrarSemanaChoferActionPerformed

    private void linkViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkViajesActionPerformed

        mostrarPanel(new ListadoViajes());

    }//GEN-LAST:event_linkViajesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Index().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private static javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JButton linkAuto;
    private javax.swing.JButton linkBalance;
    private javax.swing.JButton linkCerrarSemanaChofer;
    private javax.swing.JButton linkChofer;
    private javax.swing.JButton linkViajes;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
