/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Chofer;

import Controller.AutoController;
import Controller.ChoferController;
import Model.Auto;
import Model.Chofer;


import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import static View.Index.mostrarPanel;

/**
 *
 * @author Compumar
 */
public class ListadoChofer extends javax.swing.JPanel {

    private ChoferController choferController;

    /**
     * Creates new form ListadoChofer
     */
    public ListadoChofer() {

        initComponents();

        this.choferController = new ChoferController();

        refreshTable();

    }

    public void refreshTable() {

        DefaultTableModel tableModel = new DefaultTableModel();

        tableModel.addColumn("Id");
        tableModel.addColumn("Nombre");
        tableModel.addColumn("DNI");
        tableModel.addColumn("Celular");
        tableModel.addColumn("Auto");
        tableModel.addColumn("Disponible");
        tlListadoChofer.setModel(tableModel);


        for(Chofer chofer : choferController.readAll()) {
            Object[] row = new Object[9];

            row[0] = chofer.getId();
            row[1] = chofer.getNombre();
            row[2] = chofer.getDni();
            row[3] = chofer.getCelular();
            row[4] = chofer.getAutoAlquilado() != null ? chofer.getAutoAlquilado().getMarca()+" "+chofer.getAutoAlquilado().getModelo() : "Tiene auto propio";
            row[5] = chofer.isDisponible() ? "Disponible" : "No Disponible";


            tableModel.addRow(row);

        }

        tlListadoChofer.setModel(tableModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlListadoChofer = new javax.swing.JTable();
        btnCrearChofer = new javax.swing.JButton();
        btnEditarChofer = new javax.swing.JButton();
        btnBorrarChofer = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(927, 590));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tlListadoChofer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "DNI", "Celular", "Auto", "Disponible"
            }
        ));
        jScrollPane1.setViewportView(tlListadoChofer);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnCrearChofer.setBackground(new java.awt.Color(12, 85, 199));
        btnCrearChofer.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearChofer.setText("Crear Chofer");
        btnCrearChofer.setBorderPainted(false);
        btnCrearChofer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearChofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearChoferActionPerformed(evt);
            }
        });

        btnEditarChofer.setBackground(new java.awt.Color(12, 85, 199));
        btnEditarChofer.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarChofer.setText("Editar Chofer");
        btnEditarChofer.setBorderPainted(false);
        btnEditarChofer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarChofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarChoferActionPerformed(evt);
            }
        });

        btnBorrarChofer.setBackground(new java.awt.Color(12, 85, 199));
        btnBorrarChofer.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarChofer.setText("Borrar Chofer");
        btnBorrarChofer.setBorderPainted(false);
        btnBorrarChofer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrarChofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarChoferActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBorrarChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditarChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCrearChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearChoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearChoferActionPerformed
        mostrarPanel(new FormChofer());
    }//GEN-LAST:event_btnCrearChoferActionPerformed

    private void btnEditarChoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarChoferActionPerformed

        //Primero verifico que haya un chofer seleccionado

        int selectedRow = tlListadoChofer.getSelectedRow();

        if (selectedRow < 0) {

            // Si no hay fila seleccionada, muestro un mensaje de error

            JOptionPane.showMessageDialog(this, "Por favor, seleccione un chofer para editar.");

        }else{

            // Si hay fila seleccionada, obtengo el id del chofer y muestro el panel de edicion

            int choferId = (int) tlListadoChofer.getValueAt(selectedRow, 0);

            // Muestro el panel de edicion de chofer, llamando al metodo read, que me devuelve el chofer con el id seleccionado.
            mostrarPanel(new FormChofer(true, choferController.read(choferId)));
        }
    }//GEN-LAST:event_btnEditarChoferActionPerformed

    private void btnBorrarChoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarChoferActionPerformed

        int selectedRow = tlListadoChofer.getSelectedRow();

        if (selectedRow < 0) {

            // Si no hay fila seleccionada, muestro un mensaje de error

            JOptionPane.showMessageDialog(this, "Por favor, seleccione un chofer para borrar.");

        } else {

            // Si hay fila seleccionada, obtengo el id del chofer

            int choferId = (int) tlListadoChofer.getValueAt(selectedRow, 0);

            // Confirmo la accion de borrado

            int confirmarAccion = JOptionPane.showConfirmDialog(this, "¿Desea borrar este chofer?", "Confirmar accion", JOptionPane.YES_NO_OPTION);

            if (confirmarAccion == JOptionPane.YES_OPTION) {

                // Llamo al metodo delete del controlador de choferes

                choferController.delete(choferId);

                // Actualizo la tabla

                refreshTable();
            }
        }
    }//GEN-LAST:event_btnBorrarChoferActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarChofer;
    private javax.swing.JButton btnCrearChofer;
    private javax.swing.JButton btnEditarChofer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tlListadoChofer;
    // End of variables declaration//GEN-END:variables
}
