/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Viajes;

import Controller.ViajeController;
import Model.Viaje;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import static View.Index.mostrarPanel;

/**
 *
 * @author Compumar
 */
public class ListadoViajes extends javax.swing.JPanel {

    private ViajeController viajeController;

    /**
     * Creates new form listadoViajes
     */
    public ListadoViajes() {

        initComponents();

        this.viajeController = new ViajeController();

        refreshTable();

    }

    //Este metodo sirve para llenar la tabla con los campos necesarios. Se llama desde el constructor.

    public void refreshTable() {

        DefaultTableModel tableModel = new DefaultTableModel();

        tableModel.addColumn("Id");
        tableModel.addColumn("Chofer");
        tableModel.addColumn("Fecha");
        tableModel.addColumn("Estado");
        tableModel.addColumn("Origen");
        tableModel.addColumn("Destino");
        tableModel.addColumn("Kilometros");
        tableModel.addColumn("Valor Km");
        tableModel.addColumn("Tarifa");
        tlListadoViaje.setModel(tableModel);


        for(Viaje viaje : viajeController.readAll()) {
            Object[] row = new Object[9];

            row[0] = viaje.getId();
            row[1] = viaje.getChofer().getNombre();
            row[2] = viaje.getFecha();
            row[3] = viaje.getEstadoViaje();
            row[4] = viaje.getOrigen();
            row[5] = viaje.getDestino();
            row[6] = viaje.getKilometros();
            row[7] = viaje.getValorKm();
            row[8] = viaje.getKilometros() * viaje.getValorKm();

            tableModel.addRow(row);

        }

        tlListadoViaje.setModel(tableModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlListadoViaje = new javax.swing.JTable();
        btnCrearViaje = new javax.swing.JButton();
        btnEditarViaje = new javax.swing.JButton();
        btnBorrarViaje = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tlListadoViaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Chofer", "Fecha", "Estado", "Origen", "Destino", "Kilometros", "Valor Km", "Tarifa"
            }
        ));
        jScrollPane1.setViewportView(tlListadoViaje);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE))
        );

        btnCrearViaje.setBackground(new java.awt.Color(12, 85, 199));
        btnCrearViaje.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearViaje.setText("Crear viaje");
        btnCrearViaje.setBorderPainted(false);
        btnCrearViaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearViajeActionPerformed(evt);
            }
        });

        btnEditarViaje.setBackground(new java.awt.Color(12, 85, 199));
        btnEditarViaje.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarViaje.setText("Editar viaje");
        btnEditarViaje.setBorderPainted(false);
        btnEditarViaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarViajeActionPerformed(evt);
            }
        });

        btnBorrarViaje.setBackground(new java.awt.Color(12, 85, 199));
        btnBorrarViaje.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarViaje.setText("Borrar viaje");
        btnBorrarViaje.setBorderPainted(false);
        btnBorrarViaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarViajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBorrarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCrearViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearViajeActionPerformed

        mostrarPanel(new FormViaje());
    }//GEN-LAST:event_btnCrearViajeActionPerformed

    private void btnEditarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarViajeActionPerformed

        //Primero verifico que haya un viaje seleccionado
        int selectedRow = tlListadoViaje.getSelectedRow();

        if (selectedRow < 0) {
            // Si no hay fila seleccionada, muestro un mensaje de error
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un viaje para editar.");
        }else{
            // Si hay fila seleccionada, obtengo el id del viaje y muestro el panel de edicion
            int viajeId = (int) tlListadoViaje.getValueAt(selectedRow, 0);

            // Muestro el panel de edicion de viaje, llamando al metodo read, que me devuelve el viaje con el id seleccionado.
            mostrarPanel(new FormViaje(true, viajeController.read(viajeId)));
        }

    }//GEN-LAST:event_btnEditarViajeActionPerformed

    private void btnBorrarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarViajeActionPerformed

        int selectedRow = tlListadoViaje.getSelectedRow();
        if (selectedRow < 0) {
            // Si no hay fila seleccionada, muestro un mensaje de error
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un viaje para borrar.");
        } else {

            // Si hay fila seleccionada, obtengo el id del viaje y lo borro

            int viajeId = (int) tlListadoViaje.getValueAt(selectedRow, 0);

            // Confirmo la accion de borrado

            int confirmarAccion = JOptionPane.showConfirmDialog(this, "¿Desea borrar este viaje?", "Confirmar accion", JOptionPane.YES_NO_OPTION);

            if (confirmarAccion == JOptionPane.YES_OPTION) {

                // Llamo al metodo delete del controlador de viajes

                viajeController.delete(viajeId);

                // Actualizo la tabla

                refreshTable();
            }
        }

    }//GEN-LAST:event_btnBorrarViajeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarViaje;
    private javax.swing.JButton btnCrearViaje;
    private javax.swing.JButton btnEditarViaje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tlListadoViaje;
    // End of variables declaration//GEN-END:variables
}
